# Generated by Django 3.0.3 on 2020-02-13 09:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peak', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peak',
            name='lat',
            field=models.DecimalField(decimal_places=7, default=1, max_digits=10, validators=[django.core.validators.MaxValueValidator(90), django.core.validators.MinValueValidator(-90)]),
        ),
        migrations.AlterField(
            model_name='peak',
            name='lon',
            field=models.DecimalField(decimal_places=7, default=1, max_digits=10, validators=[django.core.validators.MaxValueValidator(180), django.core.validators.MinValueValidator(-180)]),
        ),
    ]
