# Generated by Django 3.0.3 on 2020-02-16 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peak', '0002_auto_20200213_0957'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPRejected',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
            ],
        ),
    ]
